
name: "Push to main branch"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    uses: ./.github/workflows/build.yaml

  release:
    needs: [build]
    uses: ./.github/workflows/release.yaml
    secrets:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

